### ISSUE TITLE
Anime images not working

### ISSUE THREAD

**Issue by Shoukko** [Shixma/animodern#6]
please, help me
I really loved your list desing: https://myanimelist.net/forum/?topicid=1478982
but i've got a probelm... all the anime icons images are not appearing, neither when I pass the mouse over the animes
How can I solve this?

**Comment by Shixma** [comment]
In the install code you can see this `@import "https://mal-image.appspot.com/anime/YOUR-USERNAME";`

Change it to this: `@import "https://mal-image.appspot.com/anime/Shoukko";`

or whatever your mal username is, if you've already done that just wait a bit, it can sometimes take a while to process.
